package bootstrap

import (
	"fmt"

	"github.com/kiwipanel/kiwpanel/pkg/database"
	"github.com/kiwipanel/kiwpanel/pkg/database/schema"
)

func FirstSetup() {
	passcode, err := ReadPasscode()
	if err != nil {
		fmt.Println("Cannot read the passcode generated by bash script located at /home/state/kiwipanel.conf")
		return
	}

	fmt.Println("Set up the panel, done - Using kiwipanel.conf")
	database.DB.Create(&schema.Panel{Version: "0.0.1", Passcode: passcode, Firsttime: true, Lock: false})
}

func Setup() {
	var panel schema.Panel
	result := database.DB.First(&panel, 1)

	if result.Error != nil {
		// Handle the error (record not found, connection issue, etc.)
		fmt.Println("Cannot connect to the database. Error:", result.Error)
		FirstSetup()
	} else if result.RowsAffected == 0 {
		// Handle the case where no record was found

		fmt.Println("No record found. Starting to setup")
	} else {
		// Record found, do something with 'panel'
		fmt.Println("ID:", panel.ID)
		fmt.Println(panel.Passcode)
		fmt.Println("Already setup")
	}

}
