#!/bin/bash

read_kiwipanel_log() {
    local info=${1}
    # File path
    file_path="/home/state/kiwipanel.conf"
    if [ -e "$file_path" ]; then
        result=$(awk -F':' -v key="$info" '$1 == key {print $2}' "$file_path")
        # Check if epoch time is found
        if [ -n "$result" ]; then
            echo "$result"
        else
            echo "Error: Unable to find $info in $file_path"
        fi
    else
        echo "Error: File $file_path not found"
    fi
}

# Call the function and capture the output in variables
install_info=$(read_kiwipanel_log "install")
passcode_info=$(read_kiwipanel_log "passcode")

# Use the captured values as needed
echo "Install info: $install_info"
echo "Passcode info: $passcode_info"

calc_size() {
    local raw=$1
    local total_size=0
    local num=1
    local unit="KB"
    if ! [[ ${raw} =~ ^[0-9]+$ ]]; then
        echo ""
        return
    fi
    if [ "${raw}" -ge 1073741824 ]; then
        num=1073741824
        unit="TB"
    elif [ "${raw}" -ge 1048576 ]; then
        num=1048576
        unit="GB"
    elif [ "${raw}" -ge 1024 ]; then
        num=1024
        unit="MB"
    elif [ "${raw}" -eq 0 ]; then
        echo "${total_size}"
        return
    fi
    total_size=$(awk 'BEGIN{printf "%.1f", '$raw' / '$num'}')
    echo "${total_size} ${unit}"
}

_exists() {
    local cmd="$1"
    if eval type type >/dev/null 2>&1; then
        eval type "$cmd" >/dev/null 2>&1
    elif command >/dev/null 2>&1; then
        command -v "$cmd" >/dev/null 2>&1
    else
        which "$cmd" >/dev/null 2>&1
    fi
    local rt=$?
    return ${rt}
}

get_opsy() {
    [ -f /etc/redhat-release ] && awk '{print $0}' /etc/redhat-release && return
    [ -f /etc/os-release ] && awk -F'[= "]' '/PRETTY_NAME/{print $3,$4,$5}' /etc/os-release && return
    [ -f /etc/lsb-release ] && awk -F'[="]+' '/DESCRIPTION/{print $2}' /etc/lsb-release && return
}

get_system_info() {
    cname=$(awk -F: '/model name/ {name=$2} END {print name}' /proc/cpuinfo | sed 's/^[ \t]*//;s/[ \t]*$//')
    cores=$(awk -F: '/^processor/ {core++} END {print core}' /proc/cpuinfo)
    freq=$(awk -F'[ :]' '/cpu MHz/ {print $4;exit}' /proc/cpuinfo)
    ccache=$(awk -F: '/cache size/ {cache=$2} END {print cache}' /proc/cpuinfo | sed 's/^[ \t]*//;s/[ \t]*$//')
    cpu_aes=$(grep -i 'aes' /proc/cpuinfo)
    cpu_virt=$(grep -Ei 'vmx|svm' /proc/cpuinfo)
    tram=$(
        LANG=C
        free | awk '/Mem/ {print $2}'
    )
    tram=$(calc_size $tram)
    uram=$(
        LANG=C
        free | awk '/Mem/ {print $3}'
    )
    uram=$(calc_size $uram)
    swap=$(
        LANG=C
        free | awk '/Swap/ {print $2}'
    )
    swap=$(calc_size $swap)
    uswap=$(
        LANG=C
        free | awk '/Swap/ {print $3}'
    )
    uswap=$(calc_size $uswap)
    up=$(awk '{a=$1/86400;b=($1%86400)/3600;c=($1%3600)/60} {printf("%d days, %d hour %d min\n",a,b,c)}' /proc/uptime)
    if _exists "w"; then
        load=$(
            LANG=C
            w | head -1 | awk -F'load average:' '{print $2}' | sed 's/^[ \t]*//;s/[ \t]*$//'
        )
    elif _exists "uptime"; then
        load=$(
            LANG=C
            uptime | head -1 | awk -F'load average:' '{print $2}' | sed 's/^[ \t]*//;s/[ \t]*$//'
        )
    fi
    opsy=$(get_opsy)
    arch=$(uname -m)
    if _exists "getconf"; then
        lbit=$(getconf LONG_BIT)
    else
        echo ${arch} | grep -q "64" && lbit="64" || lbit="32"
    fi
    kern=$(uname -r)
    disk_total_size=$(
        LANG=C
        df -t simfs -t ext2 -t ext3 -t ext4 -t btrfs -t xfs -t vfat -t ntfs -t swap --total 2>/dev/null | grep total | awk '{ print $2 }'
    )
    disk_total_size=$(calc_size $disk_total_size)
    disk_used_size=$(
        LANG=C
        df -t simfs -t ext2 -t ext3 -t ext4 -t btrfs -t xfs -t vfat -t ntfs -t swap --total 2>/dev/null | grep total | awk '{ print $3 }'
    )
    disk_used_size=$(calc_size $disk_used_size)
    tcpctrl=$(sysctl net.ipv4.tcp_congestion_control | awk -F ' ' '{print $3}')
}

get_system_info

IPADDRESS=$(curl -s -L -sk --connect-timeout 10 --retry 3 --retry-delay 0 http://cpanel.net/showip.cgi)
echo "IP ${IPADDRESS}"

readonly RAM=$(LC_ALL=C free -m | awk '/Mem:/ { print $2 }')
echo "RAM ${RAM}"
readonly current_swap=$(free | awk '/^Swap:/ {print $3}')
echo "current_swap ${current_swap}"

create_swap() {
    # Get the total amount of RAM in kilobytes
    total_ram_kb=$(grep MemTotal /proc/meminfo | awk '{print $2}')
    # Calculate the size for the swap file (assuming the same size as RAM)
    swap_size_kb=$total_ram_kb
    # Create a swap file
    sudo fallocate -l ${swap_size_kb}K /swapfile
    # Set appropriate permissions for the swap file
    sudo chmod 600 /swapfile
    # Make it a swap file
    sudo mkswap /swapfile
    # Enable the swap file
    sudo swapon /swapfile
    # Add an entry to /etc/fstab to make the swap file persistent
    echo "/swapfile none swap sw 0 0" | sudo tee -a /etc/fstab
}

readonly UPDATE_LINK="https://install.kiwipanel.org/update.txt"
function get_update_version() {
    PARAMETER=$1
    VERSION=$(curl -s "${UPDATE_LINK}" | grep "${PARAMETER}=" | cut -f2 -d'=')
    # Return the version
    echo "${VERSION}"
}

# Example usage:
phpmyadmin_version=$(get_update_version phpmyadmin_version)
mariadb_version=$(get_update_version mariadb_version)

echo "PHPMYADMIN_VERSION: $phpmyadmin_version"
echo "MARIADB_VERSION: $mariadb_version"

function PrintGreen() {
    local GREEN='\033[0;32m'
    local NC='\033[0m'
    local content="${1}"
    printf "${GREEN}${content}${NC}\n"
}

function generatePassword {
    LENGTH="16"
    if [ ! -z "$1" ]; then
        LENGTH="$1"
    fi
    echo $(openssl rand -base64 64 | tr -dc a-zA-Z0-9=+ | fold -w ${LENGTH} | head -1)
}

# Example usage:
password=$(generatePassword 12)
echo "Generated Password: $password"

function SetLogFile {
    export LOG_FILE="/tmp/install_kiwipanel.debug"

    if [ -f "$LOG_FILE" ]; then
        rm "$LOG_FILE"
    fi

    exec 3>&1
    exec &>$LOG_FILE
}

SetLogFile

function install_nginx() {
    #By default- running apt-get install nginx will not install the latest (stable/mainline) version of nginx as it is pulled from Ubuntu repository.
    #Reference - install the latest stable version: http://nginx.org/en/linux_packages.html#Ubuntu
    sudo apt install curl gnupg2 ca-certificates lsb-release ubuntu-keyring
    sudo curl https://nginx.org/keys/nginx_signing.key | gpg --dearmor |
        sudo tee /usr/share/keyrings/nginx-archive-keyring.gpg >/dev/null

    echo "deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] \
    http://nginx.org/packages/ubuntu $(lsb_release -cs) nginx" |
        sudo tee /etc/apt/sources.list.d/nginx.list

    echo -e "Package: *\nPin: origin nginx.org\nPin: release o=nginx\nPin-Priority: 900\n" |
        sudo tee /etc/apt/preferences.d/99nginx

    sudo apt update && apt -y install nginx
    sudo systemctl start nginx
    sudo systemctl enable nginx
}

function check_debian() {
    readonly distro=$(grep -oP 'PRETTY_NAME="\K[^"]+' /etc/os-release | cut -f1 -d' ')
    readonly distro_version=$(echo $(lsb_release -c | cut -d':' -f 2))
    echo "distro_version: $distro_version"

    if [[ "$distro" == "Debian" ]]; then
        DebianCheck=$(cat /etc/debian_version)
        
         if [[ "${DebianCheck}" < "10" ]]; then
            echo "Warning: Debian ${DebianCheck} is not supported by KiwiPanel, use Debian 11 or 12 to install"
            exit 1
        fi

    fi
}

check_debian


#!/bin/bash

# Function to check if a port is in use
check_port_usage() {
    local port_number=$1    
    # Check if lsof is installed [Will be surely installed]
    if ! [ -x "$(command -v lsof)" ]; then
        echo 'Error: lsof is not installed. Please install lsof to use this script.' >&2
        return 1
    fi
    # Check if the port is in use
    if lsof -i :$port_number >/dev/null 2>&1; then
        echo "Port $port_number is in use. You might check your compute as KiwiPanel will run on the port 8443."
    else
        echo "Port $port_number is not in use."
    fi
}

# Usage example: check_port_usage 1234
check_port_usage 8443


#!/bin/bash

KIWIPANEL="/home/state/kiwipanel.conf"

if [ -f "$KIWIPANEL" ]; then
    echo "Your server has the KIWIPANEL script installed. Please log into it using your personal confidential account."
fi

# Ask for instructions regardless of whether the kiwipanel.conf file is found
echo "What would you like to do?"
echo "1. Start KIWIPANEL"
echo "2. Stop KIWIPANEL"
echo "3. Check KIWIPANEL status"
echo "4. Exit"

read -rp "Enter your choice (1-4): " choice
case "$choice" in
    1)
        echo "Starting KIWIPANEL..."
        # Add your commands to start KIWIPANEL here
        ;;
    2)
        echo "Stopping KIWIPANEL..."
        # Add your commands to stop KIWIPANEL here
        ;;
    3)
        echo "Checking KIWIPANEL status..."
        # Add your commands to check KIWIPANEL status here
        ;;
    4)
        echo "Exiting..."
        exit 0
        ;;
    *)
        echo "Invalid choice. Exiting..."
        exit 1
        ;;
esac
