#!/bin/bash

read_kiwipanel_log() {
    local info=${1}
    # File path
    file_path="/home/state/kiwipanel.conf"    
    if [ -e "$file_path" ]; then
        result=$(awk -F':' -v key="$info" '$1 == key {print $2}' "$file_path")
        # Check if epoch time is found
        if [ -n "$result" ]; then
            echo "$result"
        else
            echo "Error: Unable to find $info in $file_path"
        fi
    else
        echo "Error: File $file_path not found"
    fi
}

# Call the function and capture the output in variables
install_info=$(read_kiwipanel_log "install")
passcode_info=$(read_kiwipanel_log "passcode")

# Use the captured values as needed
echo "Install info: $install_info"
echo "Passcode info: $passcode_info"
