#!/bin/bash
#######################################################
# KiwiPanel Installer v0.0.1
# To install KiwiPanel type:
# curl -sLO # curl -sLO https://install.kiwipanel.org/install && chmod +x install && sudo bash install
# @author: Vuong Nguyen and contributors
# @website: https://kiwipanel.org
# @since: 2024
#######################################################
clear;
LANG=en_US.UTF-8
kiwipanel_d_start_time=$(date +%s)
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' #NC: Not color: reset color to the default

function PrintGreen() {
    local GREEN='\033[0;32m'
    local NC='\033[0m'
    local content="${1}"
    printf "${GREEN}${content}${NC}\n"
}

function PrintRed() {
    local RED='\033[0;31m'
    local NC='\033[0m'
    local content="${1}"
    printf "${RED}${content}${NC}\n"
}

function welcome(){
    clear
    printf "${GREEN}========================================================\n${NC}"
    echo   "                   KIWIPANEL.ORG Scripts                  "
    echo   "            Auto Install & Optimize LEMP Stack            "
    printf "${GREEN}========================================================\n${NC}"        
    echo ""    
    PrintGreen "Installing KiwiPanel..."
    sleep 3
}

# Check for sudo/root privileges
if [[ $(whoami) != "root" ]]; then	
    PrintRed "You should install KiwiPanel as root or using sudo"
	exit 1
fi

# Control Panel path
# @credit: https://github.com/sanvu88/lempstack/blob/master/install
CPANEL="/usr/local/cpanel/cpanel"
DIRECTADMIN="/usr/local/directadmin/custombuild/build"
PLESK="/usr/local/psa/version"
WEBMIN="/etc/init.d/webmin"
SENTORA="/root/passwords.txt"
HOCVPS="/etc/hocvps/scripts.conf"
VPSSIM="/home/vpssim.conf"
EEV3="/usr/local/bin/ee"
WORDOPS="/usr/local/bin/wo"
KUSANAGI="/home/kusanagi"
CWP="/usr/local/cwpsrv"
VESTA="/usr/local/vesta/"
EEV4="/opt/easyengine"
LARVPS="/etc/larvps/.info.conf"
TINO="/opt/tinopanel"

function check_panel_script(){
  PrintGreen "Checking the current script or panel, if any...."
  sleep 3;  
  if [ -f /var/cpanel/cpanel.config ]; then
    clear    
    PrintRed "Your server installed WHM/Cpanel, please reinstall to use KiwiPanel"
    exit
    fi

    if [ -f /etc/psa/.psa.shadow ]; then
    clear
    echo "Your server installed Plesk, please reinstall to use KiwiPanel."
    exit
    fi

    if [ -f /etc/init.d/directadmin ]; then
    clear
    echo "Your server installed DirectAdmin, please reinstall to use KiwiPanel."
    exit
    fi

    if [ -f /etc/init.d/webmin ]; then
    clear
    echo "Your server installed Webmin, please reinstall to use KiwiPanel."
    exit
    fi
    PrintGreen "That is good! The VPS is freshly installed. You are good to go..."
    sleep 2
}

#Check the ARCHITECTURE
#Ref: https://raw.githubusercontent.com/runtipi/runtipi/master/scripts/install.sh
# Not supported on 32 bits systems. 
# Note: aarch64 [ARM 64-bit (also known as AArch64), armv7: 32-bit ARM]
ARCHITECTURE="$(uname -m)"
if [[ "$ARCHITECTURE" == "armv7"* ]] || [[ "$ARCHITECTURE" == "i686" ]] || [[ "$ARCHITECTURE" == "i386" ]]; then
  PrintRed "KiwiPanel is not supported on 32 bits systems"
  exit 1
fi

# Check the current distro and the kernel
readonly distro=$(grep -oP 'PRETTY_NAME="\K[^"]+' /etc/os-release | cut -f1 -d' ')
readonly kernel_version=$(uname -r)
readonly distro_version=`echo $(lsb_release -c | cut -d':' -f 2)`

echo "Your current Kernel: ${kernel_version}"
echo "Your current Linux distro: ${distro}"

function check_os() {
    if [[ "$distro" != "Ubuntu" ]]; then
        echo "$(tput setaf 1)The current version of KiwiPanel only works on Ubuntu.$(tput sgr0)"
        exit 1
    fi
}

IP=`curl -s -L http://cpanel.net/showip.cgi`
echo "$(tput setaf 2)Your IP address: $IP$(tput sgr0)" 
sleep 3;  

function check_file_availability() {
  if [ -e "$1" ]; then
    return 0  # File exists, return true (0)
  else
    return 1  # File does not exist, return false (non-zero)
  fi
}

function UpdateUbuntu(){
    printf " \n"
    echo "$(tput setaf 2)Updating the system....$(tput sgr0)"     
    sleep 3;
    sudo apt-get update && sudo apt-get -y upgrade
}


function BaseCentos(){   
    printf " \n"
    echo "$(tput setaf 2)Installing the base tools....$(tput sgr0)" 
    sleep 3;         
    sudo yum install wget curl git-all zip nano -y
}

function BaseUbuntu(){    
    printf " \n"
    echo "$(tput setaf 2)Installing the base tools....$(tput sgr0)" 
    sleep 3;    
    sudo apt install wget curl git-all zip nano -y

}

 # Install the base system for the specified distribution.
function installBase(){      
    if [ "$distro" == "Ubuntu" ]; then
        UpdateUbuntu
        BaseUbuntu
    elif [ "$distro" == "AlmaLinux" ] || [ "$distro" == "Centos" ] || [ "$distro" == "RockyLinux" ]; then
        BaseCentos
    fi
}


function Clone(){  
  cd /home
  sudo git clone https://github.com/kiwipanel/scaffolding.git
  cd scaffolding
  go build -o bin/kiwipanel
}

open_port() {
    local port=$1
    # Check if UFW is installed
    if ! command -v ufw &> /dev/null; then
        echo "UFW is not installed. Installing..."
        sudo apt-get install ufw
    fi
    # Allow the specified port
    sudo ufw allow $port
    # Reload UFW
    sudo ufw reload
    # Display status
    sudo ufw status
}


function removeFile() {
    cd /usr/bin
    if check_file_availability "$1"; then
        sudo rm "$1"
    fi
}

function moveFile() {
    # usr: unix system resources
    sudo mv -v kiwi /usr/bin
    sudo chmod 755 /usr/bin/kiwi    
}

# Function to generate a random string
generate_random_string() {
    cat /dev/urandom | tr -dc 'a-z0-9' | head -c 9
}


function create_passcode(){  
  folder_path="/home/state"    
  file_path="$folder_path/passcode.txt"  
  # Create the folder if it doesn't exist
    if [ ! -d "$folder_path" ]; then
        mkdir -p "$folder_path"
        echo "Folder created: $folder_path"
    else
        echo "Folder already exists: $folder_path"
    fi
  # Create the file if it doesn't exist
    if [ ! -e "$file_path" ]; then
        touch "$file_path"
        echo "File passcode.txt created: $file_path"
    else
        echo "File passcode.txt already exists: $file_path"
        echo "Passcode will be updated"
    fi

 readonly random_string=$(generate_random_string)
  # Write the random string to the file
  echo "$random_string" > "$file_path"
  # Print a message indicating success
  echo "Random string written to $file_path"
}

function create_database() {
    folder_path="/home/state/database"
    file_path="$folder_path/kiwipanel.sqlite"
    # Create the folder if it doesn't exist
    if [ ! -d "$folder_path" ]; then
        mkdir -p "$folder_path"
        echo "Folder created: $folder_path"
    else
        echo "Folder already exists: $folder_path"
    fi

    # Create the file if it doesn't exist
    if [ ! -e "$file_path" ]; then
        touch "$file_path"
        echo "File created: $file_path"
    else
        echo "File already exists: $file_path"
    fi

    chmod +w $file_path
    chown $(whoami):$(whoami) $file_path #Make sure that the current user own the file (root in this case) (TODO: Switch back in dashboard)
}

function create_state(){
  create_passcode
  create_database
}

function StartSystem(){
    sudo systemctl start kiwipanel
    #Will restart automatically when VPS restarts
    sudo systemctl enable kiwipanel 
}

function Success(){
    StartSystem

    printf " \n"
    
    PrintGreen "Kiwiscript has been successfully installed on your VPS!"
    kiwipanel_d_end_time=$(date +%s)
    elapsed=$((kiwipanel_d_end_time - kiwipanel_d_start_time))     
    echo "$(tput setaf 2)Total time installed: ${elapsed} seconds.$(tput sgr0)"      
    printf " \n"     
    echo "    
    "$(tput setaf 2)================================Install KiwiPanel Done!==============================$(tput sgr0)"        
    
    Register and Login at : http://$IP:8443/$random_string     

    "$(tput setaf 2)=====================================================================================$(tput sgr0)"    
    "
}


#install nginx https://gist.github.com/Dryam/3cd2e55a19e1954f1433
welcome
check_panel_script
check_os
installBase
removeFile "kiwi"
Clone
moveFile
open_port 8443
create_state
Success
# rm install


