CREATE TABLE IF NOT EXISTS domains (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  domain TEXT NOT NULL UNIQUE,
  user TEXT NOT NULL,
  php_version TEXT NOT NULL,
  docroot TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);